# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a8c27e90ed8a4711f5bc708c97c2407a355426273a553e4b4c65bf4c4532bd046caac685bbdecfc63c9e7122cee14aceec5b4f71d8d90b87aaa9d1ad68093d8

test:
  secret_key_base: 0ee1af72a07f9dda177084c61234c9713b24ec3dbc1c84cb1f68b7faeb9a493245e72121236f81111c82a03d538283091f65f48b1d3220b4356b523584b8e0bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a9eaa9e08f6254318e723984f1483842fa0b1a4660d86d1cc20f659f58c82264ba321980cd2005a48a54889787e074520551100ead9d6378c71225859812d3ba
